import express from "express";
import cors from "cors";
import pool from "./db.js";

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

app.get("/api", (req, res) => {
  res.json({ message: "Your backend is connected!" });
});

// CONNECTION TEST
app.get("/api/test-db", async (req, res) => {
  try {
    const [rows] = await pool.query("SELECT NOW() AS db_time");

    console.log(`Connection active. Current DB Time: ${rows[0].db_time}`);

    res.json({
      status: "connected",
      message: "Database is active",
      databaseTime: rows[0].db_time,
    });
  } catch (error) {
    console.error("[Database Log Error] Connection failed:", error.message);

    res.status(500).json({
      status: "error",
      message: "Failed to communicate with the database.",
      error: error.message,
    });
  }
});

// MAIN FEATURES
// LOGIN
app.post("/api/login", async (req, res) => {
  const { username, password } = req.body;

  try {
    const [users] = await pool.query(
      "SELECT id, name, role FROM Users WHERE name = ? AND password_hash = ?",
      [username, password],
    );

    if (users.length === 0) {
      return res.status(401).json({
        success: false,
        message: "Invalid username or password.",
      });
    }

    const loggedInUser = users[0];
    res.json({
      success: true,
      message: "Login successful! 🎉",
      user: {
        id: loggedInUser.id,
        name: loggedInUser.name,
        role: loggedInUser.role,
      },
    });
  } catch (error) {
    console.error("Login route error:", error.message);
    res
      .status(500)
      .json({ success: false, message: "Server error during login." });
  }
});

// INVENTORY
// 1. GET ALL PRODUCTS
app.get("/api/products", async (req, res) => {
  try {
    const [rows] = await pool.query("SELECT * FROM Products ORDER BY name ASC");
    res.json(rows);
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// 2. ADD NEW PRODUCT
app.post("/api/products", async (req, res) => {
  const { name, category, price, qty, dateAdded, expiry } = req.body;
  try {
    const query = `INSERT INTO Products (name, category, price, qty, dateAdded, expiry) VALUES (?, ?, ?, ?, ?, ?)`;
    const [result] = await pool.query(query, [
      name,
      category,
      price,
      qty,
      dateAdded,
      expiry,
    ]);
    res.json({
      success: true,
      message: "Product added!",
      insertId: result.insertId,
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// 3. UPDATE EXISTING PRODUCT
app.put("/api/products/:id", async (req, res) => {
  const { id } = req.params;
  const { name, category, price, qty, expiry } = req.body;
  try {
    const query = `UPDATE Products SET name = ?, category = ?, price = ?, qty = ?, expiry = ? WHERE id = ?`;
    await pool.query(query, [name, category, price, qty, expiry, id]);
    res.json({ success: true, message: "Product updated!" });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// 4. DELETE PRODUCT
app.delete("/api/products/:id", async (req, res) => {
  const { id } = req.params;
  try {
    await pool.query("DELETE FROM Products WHERE id = ?", [id]);
    res.json({ success: true, message: "Product deleted." });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// SALES
app.get("/api/sales", (req, res) => {
  pool.getConnection((err, connection) => {
    if (err) return res.status(500).json({ error: err.message });

    connection.query(
      "SELECT * FROM sales ORDER BY datetime DESC",
      (queryErr, results) => {
        connection.release();
        if (queryErr) return res.status(500).json({ error: queryErr.message });
        res.json(results);
      },
    );
  });
});

// POST: Record sale & deduct stock
app.post("/api/sales", (req, res) => {
  const { productId, productName, category, qty, price, total, datetime } =
    req.body;

  let formattedDateTime = datetime
    ? new Date(datetime).toISOString().slice(0, 19).replace("T", " ")
    : new Date().toISOString().slice(0, 19).replace("T", " ");

  pool.getConnection((err, connection) => {
    if (err)
      return res.status(500).json({ success: false, message: err.message });

    // Note: If your sales table uses string IDs generated by the database, ensure it is set up or add it to the query fields.
    const insertSaleQuery = `INSERT INTO sales (datetime, productName, category, qty, price, total) VALUES (?, ?, ?, ?, ?, ?)`;

    connection.query(
      insertSaleQuery,
      [formattedDateTime, productName, category, qty, price, total],
      (insertErr) => {
        if (insertErr) {
          connection.release();
          return res
            .status(500)
            .json({ success: false, message: insertErr.message });
        }

        const updateStockQuery = `UPDATE products SET qty = qty - ? WHERE id = ?`;
        connection.query(updateStockQuery, [qty, productId], (stockErr) => {
          connection.release();
          if (stockErr)
            return res
              .status(500)
              .json({ success: false, message: stockErr.message });

          res.json({ success: true, message: "Sale logged successfully." });
        });
      },
    );
  });
});

// ── DELETE: REMOVE SINGLE TRANSACTION & RESTORE STOCK ──
app.delete("/api/sales/:id", (req, res) => {
  const saleId = req.params.id;

  pool.getConnection((err, connection) => {
    if (err)
      return res.status(500).json({ success: false, message: err.message });

    connection.query(
      "SELECT productName, qty FROM sales WHERE id = ?",
      [saleId],
      (fetchErr, results) => {
        if (fetchErr || !results.length) {
          connection.release();
          return res.status(500).json({
            success: false,
            message: "Record missing or error encountered.",
          });
        }

        const { productName, qty } = results[0];

        connection.query(
          "UPDATE products SET qty = qty + ? WHERE name = ?",
          [qty, productName],
          (stockErr) => {
            if (stockErr) {
              connection.release();
              return res
                .status(500)
                .json({ success: false, message: stockErr.message });
            }

            connection.query(
              "DELETE FROM sales WHERE id = ?",
              [saleId],
              (deleteErr) => {
                connection.release();
                if (deleteErr)
                  return res
                    .status(500)
                    .json({ success: false, message: deleteErr.message });
                res.json({ success: true });
              },
            );
          },
        );
      },
    );
  });
});

// ── DELETE: CLEAR FULL SYSTEM LEDGER & RESTORE ALL QUANTITIES ──
app.delete("/api/sales", (req, res) => {
  pool.getConnection((err, connection) => {
    if (err)
      return res.status(500).json({ success: false, message: err.message });

    connection.query(
      "SELECT productName, qty FROM sales",
      (fetchErr, results) => {
        if (fetchErr) {
          connection.release();
          return res
            .status(500)
            .json({ success: false, message: fetchErr.message });
        }

        if (results.length === 0) {
          connection.query("TRUNCATE TABLE sales", (truncateErr) => {
            connection.release();
            if (truncateErr) return res.status(500).json({ success: false });
            return res.json({ success: true });
          });
          return;
        }

        let completedQueries = 0;
        results.forEach((sale) => {
          connection.query(
            "UPDATE products SET qty = qty + ? WHERE name = ?",
            [sale.qty, sale.productName],
            (updateErr) => {
              completedQueries++;

              if (completedQueries === results.length) {
                connection.query("TRUNCATE TABLE sales", (truncateErr) => {
                  connection.release();
                  if (truncateErr)
                    return res.status(500).json({ success: false });
                  res.json({ success: true });
                });
              }
            },
          );
        });
      },
    );
  });
});

// ── DELETE: CLEAR FULL SYSTEM LEDGER & RESTORE ALL QUANTITIES ──
app.delete("/api/sales", (req, res) => {
  pool.getConnection((err, connection) => {
    if (err)
      return res.status(500).json({ success: false, message: err.message });

    // Step 1: Collect every sales history block for massive stock verification calculations
    connection.query(
      "SELECT productName, qty FROM sales",
      (fetchErr, results) => {
        if (fetchErr) {
          connection.release();
          return res
            .status(500)
            .json({ success: false, message: fetchErr.message });
        }

        // If ledger is empty, skip straight to clean truncation process safely
        if (results.length === 0) {
          connection.query("TRUNCATE TABLE sales", (truncateErr) => {
            connection.release();
            if (truncateErr) return res.status(500).json({ success: false });
            return res.json({ success: true });
          });
          return;
        }

        // Step 2: Loop processing loops to restore original stock levels for every entry
        let completedQueries = 0;
        results.forEach((sale) => {
          connection.query(
            "UPDATE products SET qty = qty + ? WHERE name = ?",
            [sale.qty, sale.productName],
            (updateErr) => {
              completedQueries++;

              if (completedQueries === results.length) {
                // Step 3: Once finished returning assets, wipe clean your tables array structure
                connection.query("TRUNCATE TABLE sales", (truncateErr) => {
                  connection.release();
                  if (truncateErr)
                    return res.status(500).json({ success: false });
                  res.json({ success: true });
                });
              }
            },
          );
        });
      },
    );
  });
});

app.listen(PORT, () => {
  console.log(`Server is running smoothly on http://localhost:${PORT}`);
});
